version: '3.8'

services:
  # --- PostgreSQL Database Service ---
  db:
    image: postgres:13
    container_name: postgres-hrm  # Match the hostname
    restart: always
    hostname: postgres-hrm  # Add fixed hostname for pgAdmin
    environment:
      # These variables set up the database defined in PG_DSN in main.py
      POSTGRES_USER: hrm_user
      POSTGRES_PASSWORD: hrm_password
      POSTGRES_DB: hrm_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      # Execute the schema setup script on container startup
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
      # Persist data outside the container
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]  # Enable query logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hrm_user -d hrm_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hrm_network

  # --- FastAPI Application Service ---
  api:
    build: .
    container_name: hrm_fastapi_app
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    environment:
      # Inject the DSN used by the FastAPI app
      DATABASE_URL: postgresql://hrm_user:hrm_password@db:5432/hrm_db
      # Set the environment variable for configuration file location
      CONFIG_FILE_PATH: "/app/config.json"
      PYTHONPATH: /app
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Ensure DB is ready before starting the app
    networks:
      - hrm_network
    # restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "description=HRM API with OpenAPI documentation at /docs"

  # --- pgAdmin4 Service ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: hrm_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:

networks:
  hrm_network:
    driver: bridge
